logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.hbm2ddl=DEBUG

logging.level.org.springframework.security: DEBUG
logging.level.org.springframework.security.oauth2: DEBUG
custom.name=naqueeb